# Generated by Django 4.1.13 on 2024-11-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=10)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12)),
                ('domicilio', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('carrera', models.CharField(max_length=100)),
                ('practica1', models.BooleanField(default=False)),
                ('practica2', models.BooleanField(default=False)),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion_empresa', models.CharField(max_length=255)),
                ('jefe_directo', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=100)),
                ('telefono_jefe', models.CharField(max_length=20)),
                ('correo_jefe', models.EmailField(max_length=254)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('horario_trabajo', models.CharField(max_length=100)),
                ('horario_colacion', models.CharField(max_length=100)),
                ('cargo_desarrollar', models.CharField(max_length=100)),
                ('depto_trabajar', models.CharField(max_length=100)),
                ('actividades_realizar', models.CharField(max_length=100)),
                ('archivo_informe_avances', models.FileField(blank=True, null=True, upload_to='informes_avances/')),
                ('intentos_subida', models.PositiveIntegerField(default=0)),
                ('archivo_informe_final', models.FileField(blank=True, null=True, upload_to='informes_finales/')),
                ('intentos_subida_final', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'estudiante_inscripcionpractica',
            },
        ),
    ]
