# Generated by Django 5.0.6 on 2024-11-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionpractica',
            name='archivo_informe_avances',
            field=models.FileField(blank=True, null=True, upload_to='informes_avances/'),
        ),
        migrations.AddField(
            model_name='inscripcionpractica',
            name='informe_avances_subido',
            field=models.BooleanField(default=False),
        ),
    ]
