# Generated by Django 4.1.13 on 2024-11-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InscripcionPractica',
        ),
    ]
