# Generated by Django 4.1.13 on 2024-10-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practica',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='practica',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='coordinador.estudiante'),
        ),
    ]
