# Generated by Django 4.1.13 on 2024-11-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainscripcion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
    ]
