# Generated by Django 5.0.6 on 2024-11-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichainscripcion',
            old_name='empresa',
            new_name='direccion_empresa',
        ),
        migrations.RenameField(
            model_name='fichainscripcion',
            old_name='fecha_fin',
            new_name='fecha_termino',
        ),
        migrations.RenameField(
            model_name='fichainscripcion',
            old_name='supervisor',
            new_name='jefe_directo',
        ),
        migrations.RemoveField(
            model_name='fichainscripcion',
            name='practica',
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='actividades_realizar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='cargo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='cargo_desarrollar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='correo_jefe',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='depto_trabajar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='horario_colacion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='horario_trabajo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='practica1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='practica2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='razon_social',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='telefono_jefe',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
