# Generated by Django 5.0.6 on 2024-12-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainscripcion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
