# Generated by Django 4.1.13 on 2024-11-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeconfidencial',
            name='nota',
            field=models.FloatField(default=0),
        ),
    ]
