# Generated by Django 5.0.6 on 2024-12-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrica',
            name='criterio1',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='criterio2',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='ponderacion_criterio1',
        ),
        migrations.AddField(
            model_name='rubrica',
            name='anexos',
            field=models.CharField(blank=True, choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='caracterizacion_empresa',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='cita_fuente',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='cohesion_coherencia',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='conclusiones',
            field=models.CharField(blank=True, choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='datos_supervisor',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='desarrollo_practica',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='extension',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='formato_establecido',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='ideas_profundizacion',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='introduccion',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='objetivo_general',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='objetivos_especificos',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='ortografia',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='portada',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='recomendaciones',
            field=models.CharField(blank=True, choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='riqueza_linguistica',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='roles_impacto',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tabla_grafico',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tercera_persona',
            field=models.CharField(choices=[('Desempeño de excelencia', 'Desempeño de excelencia'), ('Desempeño efectivo', 'Desempeño efectivo'), ('Desempeño que se debe mejorar', 'Desempeño que se debe mejorar'), ('Desempeño insatisfactorio', 'Desempeño insatisfactorio')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
