# Generated by Django 5.1.1 on 2024-10-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0002_alter_practica_estado_alter_practica_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('domicilio', models.CharField(max_length=250)),
            ],
        ),
    ]
