# Generated by Django 4.1.13 on 2024-11-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0002_practicaconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicaconfig',
            name='fecha_inicio_limite',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='practicaconfig',
            name='fecha_termino_limite',
            field=models.DateField(default='2024-12-31'),
        ),
    ]
