# Generated by Django 5.0.6 on 2024-12-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0002_remove_rubrica_criterio1_remove_rubrica_criterio2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
