# Generated by Django 4.1.13 on 2024-11-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0002_informeconfidencial_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeconfidencial',
            name='nota',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
