# Generated by Django 5.0.6 on 2024-11-21 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0002_rename_empresa_fichainscripcion_direccion_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainscripcion',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coordinador.estudiante'),
            preserve_default=False,
        ),
    ]
