# Generated by Django 5.0.6 on 2024-12-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0003_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainscripcion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Jefe Carrera', 'Jefe Carrera')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='practica',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=50),
        ),
    ]
