# Generated by Django 5.0.6 on 2024-11-21 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0003_fichainscripcion_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainscripcion',
            name='practica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coordinador.practica'),
            preserve_default=False,
        ),
    ]
