# Generated by Django 5.1.1 on 2024-10-31 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0003_coordinadores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinadores',
        ),
    ]
