# Generated by Django 5.1.1 on 2024-10-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0004_delete_coordinadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='apellido',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='carrera',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='domicilio',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='nombre',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='numero_telefono',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='rut',
            field=models.CharField(default='None', max_length=20, unique=True),
        ),
    ]
