# Generated by Django 5.0.6 on 2024-12-01 20:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0004_alter_fichainscripcion_estado_alter_practica_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainscripcion',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
