# Generated by Django 5.1.1 on 2024-10-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0005_coordinador_apellido_coordinador_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
