# Generated by Django 5.1.1 on 2024-10-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0007_alter_coordinador_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='carrera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='rut',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
