# Generated by Django 5.0.6 on 2024-11-24 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0007_fichainscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practica',
            name='fecha_inscripcion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
