# Generated by Django 5.1.1 on 2024-11-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0008_alter_coordinador_apellido_alter_coordinador_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='rut',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
