# Generated by Django 5.0.6 on 2024-11-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0008_alter_practica_fecha_inscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoevaluacion',
            options={'verbose_name': 'Autoevaluación', 'verbose_name_plural': 'Autoevaluaciones'},
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='comentarios1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='comentarios2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='comentarios3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta1',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Frecuentemente', 'Frecuentemente'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta10',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Frecuentemente', 'Frecuentemente'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta11',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Frecuentemente', 'Frecuentemente'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta12',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta2',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Frecuentemente', 'Frecuentemente'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta3',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Frecuentemente', 'Frecuentemente'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta4',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Frecuentemente', 'Frecuentemente'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta5',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Frecuentemente', 'Frecuentemente'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta6',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Frecuentemente', 'Frecuentemente'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta7',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Frecuentemente', 'Frecuentemente'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta8',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Frecuentemente', 'Frecuentemente'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta9',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Frecuentemente', 'Frecuentemente'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
