# Generated by Django 5.0.6 on 2024-11-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0009_alter_autoevaluacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoevaluacion',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
