# Generated by Django 5.0.6 on 2024-11-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0010_alter_autoevaluacion_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoevaluacion',
            name='observaciones',
            field=models.TextField(null=True),
        ),
    ]
