# Generated by Django 5.1.1 on 2024-11-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0010_remove_coordinador_usuario_coordinador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='correo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
