# Generated by Django 5.1.1 on 2024-11-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0011_coordinador_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinador',
            old_name='numero_telefono',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='coordinador',
            name='apellido',
        ),
    ]
