# Generated by Django 5.0.6 on 2024-11-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0011_alter_autoevaluacion_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeavances',
            name='nota_avance',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
