# Generated by Django 5.1.1 on 2024-11-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0012_rename_numero_telefono_coordinador_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
