# Generated by Django 5.0.6 on 2024-11-26 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0013_alter_informeavances_rubrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informefinal',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='informefinal',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.rubrica'),
        ),
    ]
