# Generated by Django 5.0.6 on 2024-11-08 03:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0013_alter_coordinador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
